YEAR = 2026
AUTHOR = "Subham Subhasis Patra"
VERSION = "4.3.8"
BUILD_VERSION = VERSION.split("-")[0]
DESKTOP_ID = "io.github.subhamsubhasispatra.idownloader"
DESKTOP_OBJECT_PATH = "/" + DESKTOP_ID.replace(".", "/")
LATEST_EXTENSION_VERSION = "2.2.0"
AUTHOR_URL = "https://github.com/SubhamSubhasisPatra"
DONATE_URL = "https://github.com/SubhamSubhasisPatra"
FEEDBACK_URL = "https://github.com/SubhamSubhasisPatra/iDownloader/issues"
EXTENSION_URL = "https://github.com/SubhamSubhasisPatra/iDownloader/tree/main/browser_extension"
FIREFOX_ADDONS_URL = EXTENSION_URL
EDGE_ADDONS_URL = EXTENSION_URL
CHROME_WEBSTORE_URL = EXTENSION_URL
